---
abstract: 'MongoDB session backend for Dancer.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-MongoDB
requires:
  Carp: 0
  Dancer::Config: 0
  Dancer::ModuleLoader: 0
  Dancer::Session::Abstract: 0
  MongoDB: 0
  perl: 5.006
  vars: 0
resources:
  homepage: http://github.com/ido50/Dancer-Session-MongoDB/tree
  repository: git://github.com/ido50/Dancer-Session-MongoDB.git
version: 0.2
